### ISSUE TITLE
没有找到chStopWordsSimple.txt文件

### ISSUE THREAD

**Issue by Brucelx** [xxx0624/QA_Model#1]
CU_KG:
       你好，十分感觉你的共享，最近在学习问答系统，学习了你的代码，在初始化train数据时，get_segment_word_list方法传入stop_word_file_path，原项目中没有这个文件，这个文件是自己编写吗？
（ps,KG 是Kevin Garnett吗）
谢谢~

**Comment by xxx0624** [comment]
这就是个分词的文件，具体可以参考jieba分词。
CU_KG无意义。
